title: "Ankur Das"
description: >
  Hi, welcome to my webpage!  
  ğŸ“§ Email: ankur@patrapetika.com  
  ğŸŒ± Lifelong learner | ğŸ’¡ Design-thinker | ğŸŒ Globally-minded

theme: jekyll-theme-minimal

logo: /photos/Ankur_image.jpg
